---
name: Dockerfile Linter

on:
  push:
    branches:
      - "main"
    paths:
      - ".devcontainer/Dockerfile.*"
      - ".devcontainer/Dockerfile"
  pull_request:
    branches:
      - "main"
    paths:
      - ".devcontainer/Dockerfile.*"
      - ".devcontainer/Dockerfile"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  run-lint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: .devcontainer/Dockerfile

  run-lint-ubuntu:
    name: Hadolint Action .ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: .devcontainer/Dockerfile.ubuntu

  run-lint-alpine:
    name: Hadolint Action .alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: .devcontainer/Dockerfile.alpine

  trivy-scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          format: "table"
          ignore-unfixed: true
          scan-type: "config"
          severity: "CRITICAL,HIGH"
          trivyignores: ".trivyignore"
