---
name: Python-Linter

on:
  push:
    branches:
      - "main"
    paths:
      - "**.py"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.py"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  lint:
    name: Python Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip, Install nox
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Lint
        shell: bash
        run: |
          nox \
          --error-on-missing-interpreters \
          --non-interactive \
          --session \
          isort \
          black \
          flake8
